"""AI 应用层常量兼容导出。

常量事实来源在 ``app.common.constants.config`` 和 ``app.common.constants.business``。
新代码不要在本模块继续新增常量，避免出现多套配置源。
"""

from __future__ import annotations

from app.common.constants.business import (
    BATCH_GET_PRODUCTS_LIMIT,
    DEFAULT_PAGE_SIZE,
    IDEMPOTENCY_TTL_AFTERSALES,
    IDEMPOTENCY_TTL_ORDER,
    KNOWLEDGE_DEIXIS_KEYWORDS,
    KNOWLEDGE_SHORT_CONTENT_TOKEN_LIMIT,
    LAST_KNOWLEDGE_REFS_MAX,
    MAX_RECENT_PRODUCTS,
    POLICY_KNOWLEDGE_TOP_K,
    PRODUCT_CANDIDATE_LIMIT,
    PRODUCT_CLARIFY_LIMIT,
    PRODUCT_KNOWLEDGE_TOP_K,
    RECENT_ORDERS_LIMIT,
)
from app.common.constants.config import (
    GRAPH_PENDING_TTL_SECONDS,
    HIGH_CONFIDENCE_GAP,
    HIGH_CONFIDENCE_SCORE,
    LLM_ENTITY_EXTRACT_MAX_TOKENS,
    PRODUCT_ATTR_EXTRACT_MAX_TOKENS,
    SCENE_RECOGNITION_MAX_TOKENS,
    SEMANTIC_RECOMMEND_MAX_TOKENS,
)

__all__ = [
    "BATCH_GET_PRODUCTS_LIMIT",
    "DEFAULT_PAGE_SIZE",
    "GRAPH_PENDING_TTL_SECONDS",
    "HIGH_CONFIDENCE_GAP",
    "HIGH_CONFIDENCE_SCORE",
    "IDEMPOTENCY_TTL_AFTERSALES",
    "IDEMPOTENCY_TTL_ORDER",
    "KNOWLEDGE_DEIXIS_KEYWORDS",
    "KNOWLEDGE_SHORT_CONTENT_TOKEN_LIMIT",
    "LAST_KNOWLEDGE_REFS_MAX",
    "LLM_ENTITY_EXTRACT_MAX_TOKENS",
    "MAX_RECENT_PRODUCTS",
    "POLICY_KNOWLEDGE_TOP_K",
    "PRODUCT_ATTR_EXTRACT_MAX_TOKENS",
    "PRODUCT_CANDIDATE_LIMIT",
    "PRODUCT_CLARIFY_LIMIT",
    "PRODUCT_KNOWLEDGE_TOP_K",
    "RECENT_ORDERS_LIMIT",
    "SCENE_RECOGNITION_MAX_TOKENS",
    "SEMANTIC_RECOMMEND_MAX_TOKENS",
]
